WisDot.Bos.StandardPlans/standard-plans-web sample/WisDot.Bos.StandardPlans/Controllers/StandardPlanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WisDot.Bos.StandardPlans.Repositories;

namespace WisDot.Bos.StandardPlans.Controllers
{

    public class StandardPlanController : Controller
    {
        private IStandardPlanRepository standardPlanRepository;

        public StandardPlanController()
        {
            this.standardPlanRepository = new StandardPlanRepository();
        }

        // GET: StandardPlan
        public ActionResult Index()
        {
            return View();
        }

        // GET: StandardPlan/Details/5
        public ActionResult Details(int id = 2)
        {
            var standardPlan = standardPlanRepository.GetStandardPlan(id);
            
            /*
            if (standardPlan == null)
            {
                return DllNotFoundException()
            }*/
            return View(standardPlan);
        }

        // GET: StandardPlan/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: StandardPlan/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: StandardPlan/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: StandardPlan/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: StandardPlan/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: StandardPlan/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WisDot.Bos.StandardPlans/standard-plans-web sample/WisDot.Bos.StandardPlans/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Standard Bridge Plans</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <img src="~/Content/Images/bos.png" id="bosLogo" />
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*Html.ActionLink("Wisconsin Standard Bridge Plans", "Search", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Get Plan", "Search", "Home")</li>
                    @*<li>@Html.ActionLink("Download History", "History", "Home")</li>*@
                    <li>@Html.ActionLink("About & Contacts", "About", "Home")</li>
                    @*<li>@Html.ActionLink("Administration", "Administration", "Home")</li>*@
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Standard Plans", "Details", "StandardPlan")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>